apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "messagebroker.fullname" . }}
  labels:
    {{- include "messagebroker.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "messagebroker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "messagebroker.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "messagebroker.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.messagebroker.config.port | default 9000 }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          envFrom:
            - configMapRef:
                name: {{ include "messagebroker.fullname" . }}-configmap
            {{- if (.Values.sealedSecret.enabled) }}
            - secretRef:
                name: {{ include "messagebroker.fullname" . }}-sealedsecret
            {{- else }}
            - secretRef:
                name: {{ include "messagebroker.fullname" . }}-secret
            {{- end }}
            {{- if and .Values.secretProviderClass.enabled .Values.secretProviderClass.secretName}}
            - secretRef:
                name: {{ .Values.secretProviderClass.secretName | quote }}
            {{- end }}
          {{- if or .Values.pvc.enabled .Values.existingClaim.enabled .Values.secretProviderClass.enabled }}
          volumeMounts:
          {{- if .Values.pvc.enabled }}
          - mountPath: {{ .Values.pvc.mountPath | quote }}
            name: volume
          {{- end }}
          {{- if .Values.existingClaim.enabled }}
          - mountPath: {{ .Values.existingClaim.mountPath | quote }}
            name: existingclaim
          {{- end }}
          {{- if .Values.secretProviderClass.enabled }}
          - mountPath: "/mnt/secrets-store"
            name: secrets-store-inline
            readOnly: true
          {{- end }}
          {{- end }}
      {{- if or .Values.pvc.enabled .Values.existingClaim.enabled .Values.secretProviderClass.enabled }}
      volumes:
        {{- if .Values.pvc.enabled }}
        - name: volume
          persistentVolumeClaim:
            claimName: {{ include "messagebroker.fullname" . }}
        {{- end }}
        {{- if .Values.existingClaim.enabled }}
        - name: existingclaim
          persistentVolumeClaim:
            claimName: {{ .Values.existingClaim.claimName | quote }}
        {{- end }}
        {{- if .Values.secretProviderClass.enabled }}
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ .Values.secretProviderClass.name | quote }}
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
