name: Semantic versioning

on:
  push:
    branches: [ master ]
    paths:
      - Chart.yaml

jobs:
  cancel-previous:
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
  
  semantic-version:
    name: Semantic release
    runs-on: ubuntu-latest
    needs: [cancel-previous]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: master
          custom_release_rules: major:major:Major Changes,minor:minor:Minor Changes,chore:patch:Chores

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI deploy to ACR
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az acr helm install-cli --client-version 3.6.3 --yes
            helm package .
            az acr helm push -n ${{ secrets.HELM_REGISTRY }} ddhub-messagebroker-${{ steps.tag_version.outputs.new_version }}.tgz

      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_version }}
          release_name: Release ${{ steps.tag_version.outputs.new_version }}